# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: baef55778649267b472e4bc344276431c9209f2c99bdeb177ede868938714f197398244337a36dac351da81ae5259c5f138489833f7c89c2f96c68a729708992

test:
  secret_key_base: 43e75720f40683e016b2973f99563abe9de4b92a4853903fcc519ad7d38858de810deeeac1e3496e10f811f855b773786eb77974421e5d2cc15e9f13b6c89651

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
